export const Icons = {
  "lock-icon": require("../../assets/icons/lock-icon.png"),
  "person-icon": require("../../assets/icons/person-icon.png"),
  "account-settings-icon": require("../../assets/icons/account-settings-icon.png"),
  "bin-icon": require("../../assets/icons/bin-icon.png"),
  "check-icon": require("../../assets/icons/check-icon.png"),
  "key-icon": require("../../assets/icons/key-icon.png"),
  "mail-icon": require("../../assets/icons/mail-icon.png"),
  "pincode-icon": require("../../assets/icons/pincode-icon.png"),
  "school-icon": require("../../assets/icons/school-icon.png"),
  "work-icon": require("../../assets/icons/work-icon.png"),
  "est-flag": require("../../assets/icons/est-flag.png"),
  "eng-flag": require("../../assets/icons/eng-flag.png"),
  "ukr-flag": require("../../assets/icons/ukr-flag.png"),
  "ger-flag": require("../../assets/icons/ger-flag.png"),
  "fin-flag": require("../../assets/icons/fin-flag.png"),
  "rus-flag": require("../../assets/icons/rus-flag.png"),
  "lat-flag": require("../../assets/icons/lat-flag.png"),
  "lit-flag": require("../../assets/icons/lit-flag.png"),
  "visibility-on": require("../../assets/icons/visibility-on.png"),
  "visibility-off": require("../../assets/icons/visibility-off.png"),
  "zoom-icon": require("../../assets/icons/zoom-icon.png"),
  "code-icon": require("../../assets/icons/code-icon.png"),
  "arrow-up-icon": require("../../assets/icons/arrow-up-icon.png"),
};
